apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: pritunl
  name: pritunl
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: pritunl
  template:
    metadata:
      annotations:
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: pritunl
    spec:
      containers:
        - env:
            - name: TZ
              value: UTC
            - name: MONGODB_URI	
              value: mongodb://mongo:27017/pritunl	
          image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/pritunl:1.29.2591.94
          name: pritunl
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 1194
            - containerPort: 1194
              protocol: UDP
            - containerPort: 1195
              protocol: UDP
          resources: {}
          securityContext:
            privileged: true
      hostname: pritunl
      restartPolicy: Always
