apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: pritunl
  name: pritunl
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: pritunl
  template:
    metadata:
      annotations:
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: pritunl
    spec:
      containers:
        - env:
            - name: TZ
              value: UTC
          image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/pritunl:1.29.2591.94
          name: pritunl
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 1194
            - containerPort: 1194
              protocol: UDP
            - containerPort: 1195
              protocol: UDP
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: pritunl-claim0
              readOnly: true
      hostname: pritunl
      restartPolicy: Always
      # volumes:
      #   - name: pritunl-claim0
      #     persistentVolumeClaim:
      #       claimName: pritunl-claim0
      #       readOnly: true
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   creationTimestamp: null
#   labels:
#     io.kompose.service: pritunl-claim0
#   name: pritunl-claim0
# spec:
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 100Mi
# status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: pritunl
  name: pritunl
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "1194"
      port: 1194
      targetPort: 1194
    - name: 1194-udp
      port: 1194
      protocol: UDP
      targetPort: 1194
    - name: "1195"
      port: 1195
      protocol: UDP
      targetPort: 1195
  selector:
    io.kompose.service: pritunl

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  template:
    metadata:
      annotations:
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:latest
          name: pritunldb
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-claim0
      hostname: pritunldb
      # volumes:
      #   - name: mongo-claim0
      #     persistentVolumeClaim:
      #       claimName: mongo-claim0
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   creationTimestamp: null
#   labels:
#     io.kompose.service: mongo-claim0
#   name: mongo-claim0
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi