version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    networks:
      - private
#    volumes:
#      - ./db:/data/db

  pritunl:
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/pritunl:1.29.2591.94
    container_name: pritunl
    hostname: pritunl
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - private
      - proxy
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
    expose:
      - 9700
    environment:
      - TZ=UTC
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
      - WIREGUARD=true
    labels:
      - traefik.port=443
      - traefik.protocol=https
      - traefik.docker.network=proxy
      - traefik.backend=pritunl
      - "traefik.http.routers.pritunl.rule=Host(`admin.mydomain.com`)"
      - "traefik.http.routers.pritunl.entrypoints=web-secure"
      - "traefik.http.routers.pritunl.tls.certresolver=mytlschallenge"

  traefik:
    image: "traefik:v2.0"
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=info@mydomain.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    labels:
      #Traefik dashboard config
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.admin.mydomain.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web-secure"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
 
      #Middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
 
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=https-redirect"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  proxy:
    external:
      name: proxy
  private:
    driver: bridge
    internal: true

